#! /usr/local/bin/bash

# Assemble and disassemble a file, for testing.

file=$1
./asm48 -f bin $file
outfile=`basename $file .asm`.bin
size=`ls -l $outfile|awk '{print $5}'`
./8039dasm $outfile 0 $size
