#! /usr/local/bin/bash

run() {
	local cmd=$1
	echo "$cmd"
	$SHELL -c "$cmd"
	if [ $? != 0 ]; then
		echo "Command failed!"
		exit 1
	fi
}

run "./asm48 -f bin test2.asm"
run "./8039dasm test2.bin 0 256 > final.asm"
run "./asm48 -f bin final.asm"
run "diff test2.asm final.asm"
run "diff test2.bin final.bin"

echo "Test passed!"
